# -*- coding: utf-8 -*-
"""Chatbot_Alura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYR92qGB-7LydK20-fyK1L4TNLxGiL0c
"""

# Commented out IPython magic to ensure Python compatibility.
# Instalação do SDK --> Software Developing Kit (Kit de Desenvolvimento de Software)
# %pip install google-genai

# Importando chave da API do Google Gemini e salvando como variável de ambiente
import os
from google.colab import userdata
os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')

from google import genai

# Configurando usuário do SDK
client = genai.Client()

# Exibindo os modelos disponíveis para uso
# for model in client.models.list():
#   print(model.name)

# Definindo modelo que será utilizado
modelo = "gemini-2.0-flash"

# Requisição para a API do Goole Gemini
resposta = client.models.generate_content(model=modelo, contents="Qual a empresa responsável pelos modelos Gemini?")

print(resposta.text)

## Criando o obejto do chatbot
chat = client.chats.create(model=modelo)

# Interagindo com o chatbot
resposta = chat.send_message("Você é um assistente pessoal e sempre responde de forma sucinta. O que é uma Inteligência Artificial?")
print(resposta.text)

# Definindo as System Instructions
from google.genai import types

chat_config = types.GenerateContentConfig(
    system_instruction="Você é um assistente pessoal e sempre responde de forma sucinta."
)

chat = client.chats.create(model=modelo, config=chat_config)

resposta = chat.send_message("O que é um computador quântico?")
print(resposta.text)

# Imprimindo histórico de perguntas/repostas do chat com o Gemini
print(chat.get_history())

prompt = input("Esperando prompt: ")

while prompt.lower() != "fim":
  resposta = chat.send_message(prompt)
  print(f"\n\nResposta:\n {resposta.text}\n")
  prompt = input("Esperando prompt: ")

display(chat.get_history())

# Definindo nova System Instruction
chat_config2 = types.GenerateContentConfig(
    system_instruction="Você é um assistente pessoal que sempre responde de forma muito sarcástica e cheia de piadas. Semelhante aos artigos do site Desciclopédia."
)

chat2 = client.chats.create(model=modelo, config=chat_config2)

resposta = chat2.send_message("O que é um computador quântico?")
print(resposta.text)